### ISSUE TITLE
Why/What/How

### ISSUE THREAD

**Issue by ZooeyMiller** [dwyl/learn-seo#1]
We need to initialise the readme with the basics of **What** SEO is, **Why** you might want to do it, and **How** to go about it.

- [x] Research SEO #2 
- [x] Write Why section #4
- [x] Write What section #10 
- [x] Write How section #12 
- [x] Further reading section #15 
~Create example #3~

**Comment by iteles** [comment]
Start with `why` 😉  https://www.ted.com/talks/simon_sinek_how_great_leaders_inspire_action
