### ISSUE TITLE
Helpful Resources 

### ISSUE THREAD

**Issue by RanaAlqrenawi** [dwyl/learn-seo#17]
https://drive.google.com/file/d/0B_N-QveYNFKbOWFTSDFLbENpbWc/view?usp=sharing

https://drive.google.com/file/d/0B7tIMf_vAzmPZVBHR1lvcktiV28/view?usp=sharing

# Todo

+ [ ] review these resources 
and ***either*** 
  + [ ] summarise them (extract the info we find relevant) 
***or*** 
  + [ ] link directly to the files 🔗
